streams/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('videos.urls')),
    url(r'^admin/', admin.site.urls),
]

videos/urls.py
from django.conf.urls import url

from . import views
from .models import Video

app_name = 'videos'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<video_id>[0-9]+)$', views.watch, name='watch'),
]

videos/models.py
from django.db import models


class Video(models.Model):
    title = models.CharField(max_length=500)


class Service(models.Model):
    title = models.CharField(max_length=500)


class VideoLink(models.Model):
    url = models.CharField(max_length=500)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)

videos/views.py
from django.shortcuts import get_object_or_404, render

from .models import *

def index(request):
	try:
		search = request.GET['search']
	except KeyError:
		search = ''

	videos = Video.objects.order_by('-id')[:6]
	output = ', '.join([v.title for v in videos])

	return render(request, 'videos/index.html', {
		'search': search,
		'videos': videos,
	})


def watch(request, video_id):

	video = get_object_or_404(Video, pk=video_id)

	return render(request, 'videos/watch.html', {
		'video': video,
	});


def search(request, search_term):

	video = get_object_or_404(Video, pk=video_id)

videos/templates/videos/index.html
{% extends 'videos/layout.html' %}
{% block content %}

{% if videos %}
<div class="videos">
	{% for video in videos %}
	<a href="{% url 'videos:watch' video.id %}" class="video">
		<img src="http://lorempixel.com/300/150/abstract" class="video-cover" />
		<span class="video-title">{{video.title}}</span>
	</a>
	{% endfor %}
</div>
{% endif %}

{% endblock %}

videos/templates/videos/layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Search</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="apple-touch-icon.png">

    <link rel="stylesheet" href="{% static "videos/css/vendor/normalize-3.0.3.css" %}">
    <link rel="stylesheet" href="{% static "videos/css/vendor/bootstrap-3.3.7.min.css" %}">
    <link rel="stylesheet" href="{% static "videos/css/vendor/font-awesome-4.7.0.min.css" %}">
    <link rel="stylesheet" href="{% static "videos/css/main.css" %}">

    <script src="{% static "videos/js/vendor/jquery-1.12.0.min.js" %}"></script>
    <script src="{% static "videos/js/application.js" %}"></script>
</head>
<body>

    <header class="navbar navbar-fixed-top">
        <div class="container">
            <form action="{% url 'videos:index' %}" method="get">
                <div class="form-group">
                    <div class="input-group input-search">
                        <span class="input-group-addon">
                            <i class="fa fa-fw fa-search"></i>
                        </span>
                        <input type="text" class="form-control" id="input-search" name="search" value="{{search}}" />
                    </div>
                </div>
            </form>
        </div>
    </header>

    <div class="wrapper">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>

</body>
</html>

videos/templates/videos/watch.html
{{ video.title }}